=== vontman/Academic_Projects/JDBC_DBMS/debug/db/test/sample/sample/table_name13.dtd
<!ELEMENT table_name13 (element)>
<!ELEMENT element (column_name1,column_name2,column_name3)>
<!ELEMENT column_name1 (#PCDATA)>
<!ATTLIST column_name1 type CDATA #FIXED "varchar">
<!ELEMENT column_name2 (#PCDATA)>
<!ATTLIST column_name2 type CDATA #FIXED "int">
<!ELEMENT column_name3 (#PCDATA)>
<!ATTLIST column_name3 type CDATA #FIXED "varchar">

=== vontman/Academic_Projects/JDBC_DBMS/debug/db/test/sample/sample/table_name13.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE table_name13 SYSTEM "table_name13.dtd">
<table_name13>
<element>
<column_name1 type="varchar">'value1'</column_name1>
<column_name3 type="varchar">'value3'</column_name3>
<column_name2 type="int">4</column_name2>
</element>
<element>
<column_name1 type="varchar">'value1'</column_name1>
<column_name2 type="int">8</column_name2>
<column_name3 type="varchar">'value3'</column_name3>
</element>
</table_name13>
